#!/bin/sh -x

case "${1}" in
   start)
      /bin/rm -rf /tmp/*

      > /var/run/utmp
      /bin/chmod 664 /var/run/utmp
      /bin/chgrp utmp /var/run/utmp
      ;;

   *)
      echo "Usage: ${0} {start}"
      exit 1
      ;;
esac
