#!/bin/sh -x

case "${1}" in
   start)
      /bin/mountpoint /dev || /bin/mount -o mode=0755,nosuid /dev
      /bin/mountpoint /proc || /bin/mount -o nosuid,noexec,nodev /proc
      /bin/mountpoint /run || /bin/mount /run
      /bin/mountpoint /sys || /bin/mount -o nosuid,noexec,nodev /sys

      /bin/mkdir -p /run/lock /run/shm
      /bin/chmod 1777 /run/lock /run/shm
      /bin/ln -sfn /run/shm /dev/shm
      ;;

   *)
      echo "Usage: ${0} {start}"
      exit 1
      ;;
esac
