#!/bin/sh -x

case "${1}" in
   start)
      /bin/hostname `cat /etc/hostname`
      /usr/bin/ifconfig lo up
      /usr/sbin/dhcpcd
      ;;

   stop)
      /usr/sbin/dhcpcd -k
      /usr/bin/ifconfig lo down
      ;;

   restart)
      ${0} stop
      /bin/sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart}"
      exit 1
      ;;
esac
