#!/bin/bash

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

trap "" INT QUIT TSTP

umask 022 # Let nobody overwrite.

[ -r /etc/sysconfig/rc.site ] && source /etc/sysconfig/rc.site

next=${1}

prev=${PREVLEVEL}

for i in $(ls -v /etc/rc.d/rc${prev}.d/S[0-9][0-9]* 2> /dev/null)
do
   suffix=${i#/etc/rc.d/rc${prev}.d/S[0-9][0-9]}
   case ${next} in
      0|6)
         ;;
      *)
         if [ ! -f /etc/rc.d/rc${next}.d/[KS][0-9][0-9]${suffix} ]
         then
            echo "### ${suffix} is left untracked ###" |& /bin/tee -a `/bin/cat /run/initlogpath`
         fi
         ;;
   esac
done

for i in $(ls -v /etc/rc.d/rc${next}.d/K[0-9][0-9]* 2> /dev/null)
do
   suffix=${i#/etc/rc.d/rc${next}.d/K[0-9][0-9]}
   case ${next} in
      0|6)
         started=/etc/rc.d/rc[S$prev].d/S[0-9][0-9]${suffix}
         ;;
      *)
         started=/etc/rc.d/rc$prev.d/S[0-9][0-9]${suffix}
         ;;
   esac
   if [ -f ${started} ]
   then
      echo |& /bin/tee -a `/bin/cat /run/initlogpath`
      echo "### ${i} ###" |& /bin/tee -a `/bin/cat /run/initlogpath`
      ${i} stop |& /bin/tee -a `/bin/cat /run/initlogpath`
   fi
done

for i in $( ls -v /etc/rc.d/rc${next}.d/S[0-9][0-9]* 2> /dev/null)
do
   suffix=${i#/etc/rc.d/rc$next.d/S[0-9][0-9]}
   started=/etc/rc.d/rc$prev.d/S[0-9][0-9]$suffix
   if [ -f ${started} ]
   then
      echo "### ${suffix} is kept started ###" |& /bin/tee -a `/bin/cat /run/initlogpath`
   else
      echo |& /bin/tee -a `/bin/cat /run/initlogpath`
      echo "### ${i} ###" |& /bin/tee -a `/bin/cat /run/initlogpath`
      ${i} start |& /bin/tee -a `/bin/cat /run/initlogpath`
   fi
done

if [ `/bin/cat /run/initlogpath` = /run/initlog ]
then
   /bin/cat /run/initlog >> /var/log/initlog
   echo /var/log/initlog > /run/initlogpath
fi
