#!/bin/bash -x

CONF=`sed -e 's/#.*//' /etc/hwclock.conf`

case "${1}" in
   start)
      /sbin/hwclock --hctosys $CONF
      ;;

   stop)
      /sbin/hwclock --systohc $CONF
      ;;

   *)
      echo "Usage: ${0} {start|stop}"
      exit 1
      ;;
esac
