#!/bin/sh -x

case "${1}" in
   start)
      /sbin/udevd --daemon
      /sbin/udevadm trigger --action=add --type=subsystems
      /sbin/udevadm trigger --action=add --type=devices
      /sbin/udevadm trigger --action=change --type=devices
      /sbin/udevadm settle
      ;;

   *)
      echo "Usage ${0} {start}"
      exit 1
      ;;
esac
